### PR TITLE
Add `getFileSize` method

### PR DESCRIPTION
**Pull request by amyboyd**
Need this for another project.

### CODE REVIEW

**Comment by amyboyd** [comment]
The scrutinizer-ci build failed because of an error on their side. That shouldn't stop this being merged.

I've tried to re-start the build there, but it just gives me an error ("Oops, it seems like you have no access to this page.").

**Comment by BernardoSilva** [comment]
Can you add one test using the `localStorage`?

**Comment by amyboyd** [comment]
@BernardoSilva Added.

**Comment by BernardoSilva** [comment]
:+1: Looking good.

**Pull request merged**
